# Library

In [20]:
import numpy as np
import pandas as pd

# Load (Internet Required)

In [21]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1Dmy11XxB85wDM37S5MTCdGrlQ4zmzmTHGIcwUIj0eyU/export?format=csv")

In [22]:
# df.head()

# Rename Columns

In [23]:
df = df.rename(columns={'Kelas \n(Kelas LAB / Survey Sampling and Methodology)' : 'Kelas'})

In [24]:
new_columns_var_y = {
    old: f"Y{i+1}"
    for i, old in enumerate(df.columns[3:23])
}

In [25]:
df = df[3:23].rename(columns=new_columns_var_y)

In [26]:
df.iloc[:, 0:5].head()

            Timestamp Kelas  Gender  Y1  Y2
3  5/13/2026 19:31:11  LB09    Pria   2   3
4  5/13/2026 21:07:03  LB09  Wanita   1   1
5  5/13/2026 22:37:42  LB09    Pria   1   1
6   5/14/2026 7:45:36  LB09    Pria   1   1
7  5/14/2026 14:19:48  LB09    Pria   3   2

In [27]:
df.iloc[:, 20:25].head()

,Y18,Y19,Y20,"Selama periode Mid Exam (Semester 4), saya yakin mampu menyelesaikan tugas atau soal yang sulit jika saya berusaha dengan sungguh-sungguh.","Selama periode Mid Exam (Semester 4), ketika menghadapi hambatan dari orang lain, saya mampu menemukan jalan tengah dan cara untuk mencapai tujuan akademik saya\n(misal: keluarga, teman, atau orang lainnya)"
3,3,4,3,3,3
4,4,4,1,3,3
5,4,5,1,4,4
6,3,5,2,4,4
7,3,3,4,3,3

In [28]:
new_columns_var_x = {
    old: f"X{i+1}"
    for i, old in enumerate(df.columns[23:33])
}

In [29]:
df = df.rename(columns=new_columns_var_x)

In [30]:
df.iloc[:, 20:25].head()

   Y18  Y19  Y20  X1  X2
3    3    4    3   3   3
4    4    4    1   3   3
5    4    5    1   4   4
6    3    5    2   4   4
7    3    3    4   3   3

In [31]:
df.iloc[:, 28:33].head()

   X6  X7  X8  X9  X10
3   4   3   4   3    4
4   3   3   3   3    3
5   4   4   4   4    4
6   4   2   3   3    3
7   3   3   3   3    3

# Split DataFrame
Variable Y for Clustering = Target<br>
VAriable X + 'Gender' + 'Kelas' + 'label' for Classification

In [32]:
var_y = df.iloc[:, 3:23]

In [33]:
var_y.head()

,Y1,Y2,Y3,Y4,Y5,Y6,Y7,Y8,Y9,Y10,Y11,Y12,Y13,Y14,Y15,Y16,Y17,Y18,Y19,Y20
3,2,3,4,4,3,3,4,2,2,3,5,4,3,4,4,2,3,3,4,3
4,1,1,2,3,3,3,4,3,3,4,2,2,2,3,3,2,1,4,4,1
5,1,1,1,1,1,3,5,4,3,5,5,1,5,1,1,1,1,4,5,1
6,1,1,5,3,4,4,2,1,5,2,5,3,5,3,1,1,4,3,5,2
7,3,2,5,4,4,3,4,4,3,5,3,3,5,3,3,2,4,3,3,4

In [34]:
df_final = pd.concat([df.iloc[:, 1:3], df.iloc[:, 23:33]], axis = 1)

In [35]:
df_final.head()

  Kelas  Gender  X1  X2  X3  X4  X5  X6  X7  X8  X9  X10
3  LB09    Pria   3   3   3   2   3   4   3   4   3    4
4  LB09  Wanita   3   3   2   2   3   3   3   3   3    3
5  LB09    Pria   4   4   4   4   4   4   4   4   4    4
6  LB09    Pria   4   4   3   2   2   4   2   3   3    3
7  LB09    Pria   3   3   2   3   3   3   3   3   3    3